name: Trigger Sync in Unisync

on:
  push:
    branches:
      - dev  # Triggers when dev is updated
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sync Workflow in Unisync
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/mda1458/unisync/actions/workflows/sync-dev-to-main.yml/dispatches \
          -d '{"ref":"main"}'
